version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "echo 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    build: .
    container_name: node-product-api
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
